### ISSUE TITLE
test a failed transaction cancellation

### ISSUE THREAD

**Issue by matin** [cuenca-mx/arcus-python#56]
We're only testing a [successful cancelation of a transaction](https://github.com/cuenca-mx/arcus-python/blob/master/tests/resources/test_bills.py#L52-L62), but what happens when the cancellation fails because it's too late to cancel?

This should be tested and the failure case should be documented.

**Comment by reqm87** [comment]
@matin I have a question for you.
We have three cases to validate of failed transaction cancellation.

**1) First case:**

Biller works with a delay with transactions to become fulfilled (status: sent).
Biller accept transaction cancellation.
I cancel the transaction twice.
I did the unit test for this case without any problem.

**2) Second case:**

Biller not accept transaction cancellation and I cancel transaction.
I did the unit test for this case without any problem.

**3) Third case:**

Biller works with transactions that become immediately fulfilled.
Biller accept transaction cancellation in the same day.
So, I need to wait one day to cancel the transaction and generate the cassette for this unit test.
It's the only way to test this case of failed transaction cancellation.
But, we could delete the cassette in the future and the unit test will fail for one day.
I think this is a problem that maybe we can have in the future.

Are you ok with this?
Or you want to skip this case? So, we will not have problems with the unit test and the build process with Travis in the future if someone delete this cassette for any reason.

Let me know your decision.
So, I can finish this unit test.

Thank you!

**Comment by matin** [comment]
## Successfully cancel a bill (scenario 1)

This looks good: https://github.com/cuenca-mx/arcus-python/blob/test-failed-txn-cancel/tests/resources/test_bills.py#L50-L60

## Attempt to cancel an bill that can't be canceled (scenario 2)

The problem is with fetching an existing transaction. In your test, it's also possible for there to be no transactions—in which case no test is actually run.

https://github.com/cuenca-mx/arcus-python/blob/test-failed-txn-cancel/tests/resources/test_bills.py#L63-L75

There are two solutions:
1. create the bill + transaction in the same test
2. use a fixture

Otherwise, running the test on it's own (instead of in the entire suite) wouldn't actually test anything.

## Cancel a fulfilled transaction

Arcus uses specific bill info to produce different scenarios. Could you check if it's possible to create a transaction that's immediately fulfilled but not cancellable?

**Comment by reqm87** [comment]
@matin About scenario 3...

There is two scenarios where it's possible to create a transaction that's immediately fulfilled but not cancellable.

**1)** When a biller lets to create a transaction that's immediately fulfilled, but not accept transaction cancellation.
_I did the unit test for this case, but I didn't pushed it to the repository yet._

**2)** When a biller lets to create a transaction that's immediately fulfilled and accepts transaction cancellation in the same day, but not accept transaction cancellation at the next day.
_**This is the case that I am asking you, because I need to wait for the next day to generate the cassette for the unit test, but we shouldn't delete this cassette because the unit test will fail because of this time restriction with this scenario.**_

**Comment by matin** [comment]
> **1)** When a biller lets to create a transaction that's immediately fulfilled, but not accept transaction cancellation.
> _I did the unit test for this case, but I didn't pushed it to the repository yet._

This is sufficient.
